-- Migration: Sample_datas - Insert_sample_datas_for_skills_experience_company
-- Created: Fri Mar 20 04:43:50 PM +07 2026
-- Author: hoangvuongbui

-- Add your SQL statements below:
-- ========================================================
-- 1. COMPANY (10 records - Professional Vietnamese IT companies)
-- ========================================================
INSERT INTO company (company_id, company_name, tax_code, size_range, overview, industry, province_code, address, logo_url, website_url) VALUES
(gen_random_uuid(), 'FPT Software', '0100109106', '1000+', 'Thành lập năm 1999, FPT Software hiện là công ty cung cấp dịch vụ công nghệ thông tin và chuyển đổi số quy mô lớn nhất Việt Nam và vươn tầm Đông Nam Á. Với mạng lưới hoạt động trải dài trên 30 quốc gia và vùng lãnh thổ, công ty chuyên cung cấp các giải pháp công nghệ toàn diện và tiên tiến nhất như Trí tuệ nhân tạo (AI), Điện toán đám mây (Cloud), Phân tích dữ liệu lớn (Big Data), Internet vạn vật (IoT) và Tự động hóa quy trình bằng robot (RPA). Trải qua hơn hai thập kỷ phát triển, FPT Software đã và đang là đối tác chiến lược quan trọng của hàng nghìn doanh nghiệp, tập đoàn trong danh sách Fortune Global 500 trên toàn cầu, đặc biệt khẳng định vị thế vững chắc tại các thị trường trọng điểm và khắt khe như Nhật Bản, Mỹ, Châu Âu và khu vực Châu Á - Thái Bình Dương.', 'Công Nghệ Thông Tin', '700000', 'Phu My Hung, District 7, HCMC', 'fpt-logo.png', 'fpt-software.com'),
 (gen_random_uuid(), 'VNG Corporation', '0302266895', '1000+', 'Chính thức thành lập vào năm 2004 với tên gọi ban đầu là Vinagame, VNG Corporation tự hào được vinh danh là kỳ lân công nghệ đầu tiên của Việt Nam. Trải qua quá trình chuyển mình mạnh mẽ, VNG hiện đang sở hữu và phát triển một hệ sinh thái công nghệ đa dạng, khép kín và toàn diện. Các mảng kinh doanh cốt lõi bao gồm giải trí trực tuyến với nền tảng VNGGames vươn tầm quốc tế, nền tảng kết nối cộng đồng với siêu ứng dụng nhắn tin Zalo phục vụ hàng chục triệu người dùng mỗi ngày, tài chính kỹ thuật số với ví điện tử ZaloPay tiên phong trong thanh toán không tiền mặt, và các giải pháp công nghệ chuyển đổi số chuyên sâu như VNG Cloud và vDesk. Công ty không ngừng đổi mới sáng tạo để thực hiện sứ mệnh kiến tạo công nghệ, phát triển con người, từ Việt Nam vươn tầm thế giới.', 'Công Nghệ Thông Tin', '700000', '9 Dinh Tien Hoang, District 1, HCMC', 'vng-logo.png', 'vng.com.vn'),
(gen_random_uuid(), 'Tiki Corporation', '0103692061', '1000+', 'Khởi đầu đầy khiêm tốn là một nền tảng chuyên phân phối sách ngoại ngữ trực tuyến vào tháng 3 năm 2010, Tiki (viết tắt của "Tìm kiếm & Tiết kiệm") hiện đã vươn mình trở thành một trong những hệ sinh thái thương mại điện tử hàng đầu và đáng tin cậy nhất tại Việt Nam. Điểm làm nên thương hiệu của Tiki chính là dịch vụ giao hàng siêu tốc TikiNOW, cùng chính sách kiểm soát chất lượng nghiêm ngặt đảm bảo 100% hàng chính hãng. Không chỉ dừng lại ở bán lẻ, Tiki còn phát triển mạnh mẽ nền tảng sàn giao dịch (Marketplace), chuỗi cung ứng logistics tích hợp (TikiNOW Smart Logistics) quy mô lớn, cùng giải pháp bán vé máy bay, bảo hiểm và dịch vụ tài chính, nhằm mang lại trải nghiệm mua sắm trọn vẹn và an tâm tuyệt đối cho người tiêu dùng.', 'Sale Bán Hàng', '700000', 'Lach Tray, District 3, HCMC', 'tiki-logo.png', 'tiki.vn'),
(gen_random_uuid(), 'VinAI Research', '0108441481', '150-500', 'Được thành lập vào tháng 4 năm 2019 dưới sự bảo trợ và đầu tư mạnh mẽ của Tập đoàn Vingroup, VinAI hiện là một trong 20 trung tâm nghiên cứu và ứng dụng Trí tuệ nhân tạo (AI) hàng đầu trên thế giới. Tập trung quy tụ những tài năng AI xuất chúng mang tầm vóc quốc tế, viện chuyên nghiên cứu sâu rộng vào các lĩnh vực mũi nhọn như Học máy (Machine Learning), Thị giác máy tính (Computer Vision) và Xử lý ngôn ngữ tự nhiên (NLP). Không chỉ dừng lại ở nghiên cứu hàn lâm với hàng loạt công bố tại các hội nghị AI danh giá nhất toàn cầu, VinAI còn chú trọng thương mại hóa công nghệ, ứng dụng AI vào các sản phẩm thực tiễn, tiêu biểu là các hệ thống hỗ trợ lái xe nâng cao (ADAS), công nghệ giám sát người lái (DMS) và các giải pháp phân tích dữ liệu hình ảnh thông minh.', 'Công Nghệ Thông Tin', '100000', 'Vincom Mega Mall Royal City, Hanoi', 'vinai-logo.png', 'vinai.io'),
(gen_random_uuid(), 'CMC Global', '0101777852', '1000+', 'Là công ty thành viên chủ lực mang trọng trách thực hiện chiến lược "Go Global" của Tập đoàn Công nghệ CMC, CMC Global chuyên cung cấp các dịch vụ gia công phần mềm, xuất khẩu công nghệ và giải pháp chuyển đổi số toàn diện đạt tiêu chuẩn quốc tế. Mặc dù là một tên tuổi tương đối trẻ khi thành lập vào năm 2017, công ty đã nhanh chóng khẳng định năng lực với quy mô lên tới hàng nghìn kỹ sư chuyên nghiệp. CMC Global có thế mạnh vượt trội trong việc triển khai và tối ưu hóa các công nghệ mới nổi như Điện toán đám mây (Cloud Computing), Trí tuệ nhân tạo (AI), Phân tích dữ liệu và Internet vạn vật (IoT). Công ty hiện là đối tác công nghệ chiến lược và tin cậy của hàng loạt tập đoàn lớn, đa quốc gia tại các thị trường trọng điểm như Nhật Bản, Hàn Quốc, Singapore và Châu Á - Thái Bình Dương.', 'Công Nghệ Thông Tin', '100000', 'Duy Tan, Cau Giay, Hanoi', 'cmc-logo.png', 'cmcglobal.com.vn'),
(gen_random_uuid(), 'Saigon Technology', '0311978999', '150-500','Thành lập năm 2012, Saigon Technology tự hào là một trong những công ty cung cấp dịch vụ gia công và phát triển phần mềm theo mô hình Agile/Scrum hàng đầu tại Việt Nam. Chuyên biệt trong việc cung cấp các dịch vụ tư vấn công nghệ chất lượng cao, đội ngũ kỹ sư và chuyên gia CNTT của công ty tập trung phục vụ đối tượng khách hàng là các startup, doanh nghiệp vừa và lớn trên toàn cầu. Khách hàng chủ lực của Saigon Technology đến từ các thị trường có tiêu chuẩn khắt khe như Bắc Mỹ, Châu Âu, Úc, Singapore và Nhật Bản. Công ty sở hữu thế mạnh chuyên sâu trong việc phát triển các ứng dụng Web phức tạp, ứng dụng di động đa nền tảng, kiến trúc vi dịch vụ (Microservices), giải pháp phần mềm dạng dịch vụ (SaaS) và điện toán đám mây, cam kết mang lại sản phẩm ưu việt và tối ưu chi phí.', 'Công Nghệ Thông Tin', '700000', 'District 1, HCMC', 'saigon-tech-logo.png', 'saigontechnology.com'),
(gen_random_uuid(), 'KMS Technology', '0304837555', '1000+', 'Chính thức đi vào hoạt động từ năm 2009, KMS Technology là công ty đa quốc gia có trụ sở chính tại Atlanta (Mỹ) cùng các trung tâm phát triển phần mềm quy mô lớn đặt tại Việt Nam. Công ty chuyên cung cấp các dịch vụ cốt lõi bao gồm phát triển phần mềm theo yêu cầu, kiểm thử và đảm bảo chất lượng phần mềm (QA & Testing), tư vấn hiện đại hóa hệ thống và triển khai các giải pháp dữ liệu tiên tiến. Đáng chú ý, KMS không chỉ đơn thuần là một đơn vị gia công mà còn là một "vườn ươm" sản phẩm công nghệ xuất sắc. Công ty đã đầu tư, nghiên cứu và tung ra thị trường toàn cầu hàng loạt sản phẩm phần mềm khởi nghiệp B2B thành công rực rỡ, được hàng triệu kỹ sư trên thế giới tin dùng, tiêu biểu như nền tảng kiểm thử tự động Katalon Studio, giải pháp quản lý kiểm thử QASymphony, Kobiton và Grove.', 'Công Nghệ Thông Tin', '700000', 'Tan Thuan Export Processing Zone, HCMC', 'kms-logo.png', 'kms-technology.com'),
(gen_random_uuid(), 'TMA Solutions', '0302892381', '1000+', 'Trải qua chặng đường hơn một phần tư thế kỷ hình thành và phát triển từ năm 1997, TMA Solutions tự hào giữ vững vị thế là một trong những tập đoàn công nghệ lớn mạnh, uy tín và có bề dày lịch sử lâu đời nhất tại Việt Nam. Sở hữu lực lượng nòng cốt gồm hơn 4.000 kỹ sư tài năng và giàu kinh nghiệm, TMA là đối tác cung cấp giải pháp công nghệ R&D và gia công phần mềm toàn diện cho các tập đoàn viễn thông, tài chính, y tế hàng đầu thế giới. Công ty đã khẳng định năng lực thực thi xuất sắc trong các dự án phức tạp đòi hỏi hàm lượng công nghệ cao như mạng 5G, hệ thống quản lý dữ liệu lớn, trí tuệ nhân tạo, bảo mật thông tin và tự động hóa công nghiệp. Hiện tại, các sản phẩm và dịch vụ do TMA tham gia phát triển đang được ứng dụng rộng rãi tại hơn 30 quốc gia và vùng lãnh thổ.', 'Công Nghệ Thông Tin', '700000', 'Tan Thuan EPZ, District 7, HCMC', 'tma-logo.png', 'tmasolutions.com'),
(gen_random_uuid(), 'Axon Active', '0313788899', '1000+', 'Kế thừa tinh hoa từ tập đoàn mẹ tại Thụy Sĩ, Axon Active là doanh nghiệp có 100% vốn đầu tư nước ngoài và được biết đến như một trong những đơn vị tiên phong, dẫn đầu trong việc đưa mô hình phát triển phần mềm linh hoạt (Agile/Scrum) vào áp dụng thực tiễn tại Việt Nam từ năm 2008. Thay vì nhận gia công dự án đơn lẻ, công ty chuyên xây dựng và quản lý các Đội ngũ chuyên trách (Offshore Development Center/Dedicated Team) hoạt động độc quyền và trực tiếp với hệ thống khách hàng. Với các văn phòng khang trang tại TP.HCM, Đà Nẵng và Cần Thơ, Axon Active chủ yếu phục vụ các đối tác và khách hàng chiến lược tại khu vực Châu Âu. Môi trường làm việc tại đây luôn đề cao sự sáng tạo, tinh thần làm việc nhóm chặt chẽ và tư duy quản lý chất lượng nghiêm ngặt của Châu Âu.', 'Công Nghệ Thông Tin', '500000', 'Chai Tower, Hai Chau, Da Nang', 'axon-logo.png', 'axonactive.com'),
(gen_random_uuid(), 'Giao Hàng Tiết Kiệm', '0106181234', '1000+', 'Bắt đầu hành trình khởi nghiệp vào năm 2013, Giao Hàng Tiết Kiệm (GHTK) không chỉ đơn thuần là một đơn vị vận chuyển mà bản chất là một công ty công nghệ (Tech-company) tiên phong hoạt động trong lĩnh vực bưu chính và e-Logistics tại Việt Nam. Nền tảng tạo nên sự khác biệt và năng lực cạnh tranh vượt trội của GHTK nằm ở việc ứng dụng triệt để công nghệ thông tin vào mọi khâu vận hành. Công ty tự làm chủ hệ thống công nghệ lõi, xử lý khối lượng Dữ liệu lớn (Big Data) khổng lồ mỗi ngày, áp dụng các thuật toán tối ưu hóa định tuyến, hệ thống phân loại hàng hóa tự động và ứng dụng di động thông minh cho hàng chục ngàn tài xế. Nhờ đó, GHTK có thể cung cấp dịch vụ giao nhận chặng cuối (last-mile delivery) với tốc độ cực nhanh với mạng lưới phủ sóng khắp 63 tỉnh thành.', 'Logistics', '100000', 'Pham Hung, Nam Tu Liem, Hanoi', 'ghtk-logo.png', 'giaohangtietkiem.vn'),
(gen_random_uuid(), 'ELSA Corp', '0314123987', '50-150', 'ELSA Corp là một trong những startup công nghệ giáo dục (EdTech) gốc Việt gây tiếng vang mạnh mẽ nhất trên trường quốc tế, được đồng sáng lập vào năm 2015. Sản phẩm cốt lõi của công ty, ứng dụng ELSA Speak, là một trợ lý ảo luyện phát âm tiếng Anh đột phá. Sức mạnh của ELSA nằm ở công nghệ nhận diện giọng nói (Speech Recognition) độc quyền được tinh chỉnh bằng Trí tuệ nhân tạo (AI) học sâu (Deep Learning), có khả năng phân tích âm thanh, phát hiện lỗi sai phát âm của người học đến từng âm tiết một cách chính xác tuyệt đối và đưa ra hướng dẫn khắc phục chi tiết như một giáo viên bản xứ. Với tiềm năng khổng lồ, ELSA đã thu hút hàng chục triệu đô la vốn đầu tư từ các quỹ đầu tư mạo hiểm hàng đầu thế giới, trong đó nổi bật nhất là quỹ Gradient Ventures chuyên về AI của Google.', 'Giáo Dục', '700000', 'District 1, HCMC', 'elsa-logo.png', 'elsaspeak.com'),
(gen_random_uuid(), 'Rikkeisoft', '0106728999', '1000+', 'Bắt đầu từ những hoài bão của một nhóm cựu du học sinh Việt Nam tại Nhật Bản vào năm 2012, Rikkeisoft nay đã vươn lên mạnh mẽ, trở thành một trong những doanh nghiệp tư nhân hàng đầu Việt Nam trong lĩnh vực xuất khẩu phần mềm và chuyển đổi số. Lấy chất lượng làm kim chỉ nam, thị trường trọng điểm của Rikkeisoft luôn là Nhật Bản, nơi họ đã xây dựng được mạng lưới khách hàng doanh nghiệp khổng lồ và thành lập nhiều chi nhánh lớn tại Tokyo, Osaka. Không dừng lại ở đó, Rikkeisoft đang trên đà hiện thực hóa chiến lược toàn cầu hóa, mở rộng dấu ấn sang thị trường Mỹ, Châu Á - Thái Bình Dương và Châu Âu. Đội ngũ hàng nghìn nhân sự của công ty tự tin làm chủ và cung cấp các giải pháp công nghệ mũi nhọn bao gồm kiến trúc Web/Cloud, ứng dụng Mobile, phát triển Game, công nghệ Blockchain, Trí tuệ nhân tạo (AI) và IoT.', 'Công Nghệ Thông Tin', '100000', 'Ba Dinh District, Hanoi', 'rikkeisoft-logo.png', 'rikkeisoft.com'),
(gen_random_uuid(), 'Viettel Group', '0100109100', '1000+', 'Tập đoàn Công nghiệp - Viễn thông Quân đội (Viettel) là doanh nghiệp viễn thông và công nghệ thông tin lớn nhất Việt Nam. Trải qua hơn 30 năm phát triển, Viettel không chỉ thống trị thị trường viễn thông nội địa mà còn đầu tư thành công tại hơn 10 quốc gia trên thế giới ở 3 châu lục. Hiện nay, Viettel đang chuyển mình mạnh mẽ từ một nhà mạng viễn thông truyền thống sang nhà cung cấp dịch vụ số, dẫn dắt quá trình chuyển đổi số quốc gia với các hệ sinh thái đa dạng bao gồm viễn thông, giải pháp CNTT, dịch vụ số, an ninh mạng và công nghiệp công nghệ cao.', 'Viễn Thông', '100000', '1 Tran Huu Duc, Nam Tu Liem, Hanoi', 'viettel-logo.png', 'viettel.com.vn'),
(gen_random_uuid(), 'MoMo (M_Service)', '0305153670', '1000+', 'Được thành lập từ năm 2007, MoMo (Công ty Cổ phần Dịch vụ Di động Trực tuyến) hiện là ví điện tử số 1 tại Việt Nam và cũng là một trong những kỳ lân công nghệ (startup được định giá trên 1 tỷ USD) hiếm hoi của quốc gia. MoMo xây dựng một siêu ứng dụng (Super App) cung cấp hàng trăm dịch vụ tiện ích, từ chuyển tiền, thanh toán hóa đơn, mua sắm trực tuyến, đến các dịch vụ tài chính, bảo hiểm và du lịch. Với hơn 30 triệu người dùng, MoMo đang từng bước thực hiện sứ mệnh thúc đẩy nền kinh tế không tiền mặt và mang các dịch vụ tài chính đến gần hơn với mọi người dân Việt Nam.', 'Tài Chính Công Nghệ', '700000', 'Phu My Hung, District 7, HCMC', 'momo-logo.png', 'momo.vn'),
(gen_random_uuid(), 'Shopee Vietnam', '0106773786', '1000+', 'Ra mắt tại Việt Nam vào năm 2015, Shopee nhanh chóng trở thành nền tảng thương mại điện tử hàng đầu không chỉ ở Việt Nam mà còn trên toàn khu vực Đông Nam Á và Đài Loan. Shopee cung cấp trải nghiệm mua sắm trực tuyến dễ dàng, an toàn và nhanh chóng thông qua sự hỗ trợ mạnh mẽ về thanh toán và vận chuyển. Thuộc sở hữu của tập đoàn công nghệ Sea Group (Singapore), Shopee Việt Nam liên tục mở rộng hệ sinh thái của mình, kết hợp thêm ví điện tử ShopeePay và dịch vụ giao đồ ăn ShopeeFood, tạo ra một trải nghiệm số toàn diện cho hàng chục triệu người tiêu dùng.', 'Thương Mại Điện Tử', '700000', 'Saigon Centre 2, District 1, HCMC', 'shopee-logo.png', 'shopee.vn'),
(gen_random_uuid(), 'VNPay', '0102182292', '1000+', 'VNPay (Công ty Cổ phần Giải pháp Thanh toán Việt Nam) là kỳ lân công nghệ thứ hai của Việt Nam, nổi bật trong lĩnh vực thanh toán điện tử. Công ty là đơn vị tiên phong phát triển và cung cấp cổng thanh toán VNPAY-QR, mạng lưới thanh toán mã QR lớn nhất và phổ biến nhất tại Việt Nam, tích hợp trên ứng dụng mobile banking của hơn 40 ngân hàng và các ví điện tử. Hệ sinh thái của VNPay (thuộc VNLife) còn mở rộng sang các giải pháp bán lẻ trực tuyến, dịch vụ đặt vé (VNPAY-Ticket) và các giải pháp phần mềm quản trị doanh nghiệp toàn diện.', 'Tài Chính Công Nghệ', '100000', 'Lang Ha, Dong Da, Hanoi', 'vnpay-logo.png', 'vnpay.vn'),
(gen_random_uuid(), 'Amanotes', '0313076893', '150-500', 'Amanotes là một startup công nghệ âm nhạc (Music-Tech) đầy tự hào của Việt Nam, được vinh danh là nhà phát hành game âm nhạc số 1 thế giới. Thành lập năm 2014, Amanotes kết hợp giữa công nghệ, âm nhạc và yếu tố trò chơi để tạo ra những ứng dụng giải trí mang tính gây nghiện cao như Magic Tiles 3 và Tiles Hop. Tính đến nay, các sản phẩm của Amanotes đã vượt mốc 3 tỷ lượt tải xuống toàn cầu với hàng triệu người dùng hoạt động mỗi ngày. Công ty đang tiếp tục đầu tư mạnh vào AI để tạo ra các trải nghiệm tương tác âm nhạc ngày càng cá nhân hóa và đột phá.', 'Sản Xuất Game', '700000', 'AB Tower, District 1, HCMC', 'amanotes-logo.png', 'amanotes.com'),
(gen_random_uuid(), 'NashTech Vietnam', '0302000000', '1000+', 'Trực thuộc tập đoàn Harvey Nash toàn cầu (Anh Quốc), NashTech là một trong những doanh nghiệp FDI có quy mô lớn nhất trong lĩnh vực xuất khẩu phần mềm và cung cấp dịch vụ công nghệ tại Việt Nam. Hoạt động tại Việt Nam từ năm 2000, NashTech sở hữu hàng ngàn kỹ sư làm việc tại TP.HCM, Hà Nội và Đà Nẵng. Công ty chuyên cung cấp các giải pháp công nghệ cao cho các thị trường Âu, Mỹ, Úc, tập trung vào Tư vấn Chuyển đổi số, Phát triển phần mềm hiện đại, Dữ liệu, Phân tích (Data Analytics) và Tự động hóa quy trình.', 'Công Nghệ Thông Tin', '700000', 'Etown, Tan Binh, HCMC', 'nashtech-logo.png', 'nashtechglobal.com'),
(gen_random_uuid(), 'Base.vn', '0107530663', '150-500', 'Thành lập năm 2016, Base.vn là đơn vị đi tiên phong trong lĩnh vực xây dựng Nền tảng quản trị doanh nghiệp SaaS (Software-as-a-Service) tại Việt Nam. Không cung cấp một phần mềm "All-in-one" cồng kềnh, Base xây dựng một hệ sinh thái các ứng dụng chuyên biệt, kết nối chặt chẽ với nhau, giải quyết từng bài toán cụ thể của doanh nghiệp từ quản trị nhân sự, quản lý công việc, quy trình, đến tài chính. Đến năm 2021, Base.vn chính thức gia nhập hệ sinh thái của Tập đoàn FPT, tạo ra một liên minh công nghệ mạnh mẽ thúc đẩy quá trình chuyển đổi số cho hàng nghìn doanh nghiệp SMEs trong nước.', 'Công Nghệ Thông Tin', '100000', 'Mac Thai Tong, Cau Giay, Hanoi', 'base-logo.png', 'base.vn'),
(gen_random_uuid(), 'Cốc Cốc', '0106161477', '150-500', 'Cốc Cốc (trước đây là Cờ Rôm+) là công ty công nghệ Việt Nam nổi tiếng nhất với việc phát triển trình duyệt web và công cụ tìm kiếm tối ưu hóa dành riêng cho người dùng Việt. Bắt đầu từ năm 2013, trình duyệt Cốc Cốc đã nhanh chóng chiếm được thị phần lớn nhờ việc thấu hiểu thói quen người Việt như hỗ trợ tải video tốc độ cao, sửa lỗi chính tả, thêm dấu tiếng Việt tự động và giải toán trực tuyến. Hiện tại, Cốc Cốc sở hữu hàng chục triệu người dùng hoạt động hàng tháng và là một trong số ít những nền tảng nội địa có đủ khả năng cạnh tranh trực tiếp với các gã khổng lồ công nghệ toàn cầu ngay tại sân nhà.', 'Công Nghệ Thông Tin', '100000', 'HITC Building, Cau Giay, Hanoi', 'coccoc-logo.png', 'coccoc.com'),
(gen_random_uuid(), 'Be Group', '0108275525', '500-1000', 'Be Group là công ty công nghệ đứng sau ứng dụng gọi xe thuần Việt "be", ra mắt vào cuối năm 2018. Lấy tiêu chí "Lấy tài xế làm cốt lõi", Be Group đã phát triển thần tốc để trở thành một trong những nền tảng dịch vụ theo yêu cầu (On-demand) lớn nhất Việt Nam, phá vỡ thế độc quyền của các đối thủ nước ngoài. Hiện tại, ngoài gọi xe công nghệ (beBike, beCar), hệ sinh thái của Be đã mở rộng sang giao hàng, giao đồ ăn, mua vé máy bay, và tích hợp ngân hàng số Cake by VPBank, hướng tới mục tiêu trở thành nền tảng tiêu dùng đa dịch vụ không thể thiếu của người Việt.', 'Công Nghệ Vận Tải', '100000', 'Sai Dong, Long Bien, Hanoi', 'be-logo.png', 'be.com.vn'),
(gen_random_uuid(), 'Sendo', '0312776486', '500-1000', 'Sendo.vn là sàn thương mại điện tử do Tập đoàn FPT phát triển từ năm 2012, hướng tới mục tiêu phục vụ thị trường người tiêu dùng nội địa, đặc biệt là ở các khu vực tỉnh lẻ, ngoại ô (Tier 2). Với định vị là một "chợ của người Việt", Sendo kết nối hàng trăm ngàn cửa hàng vừa và nhỏ với hàng triệu khách hàng trên toàn quốc. Sàn TMĐT này có thế mạnh trong việc ứng dụng các giải pháp công nghệ AI và Big Data từ FPT để cá nhân hóa người dùng, tối ưu hóa quá trình tìm kiếm sản phẩm và vận hành hệ thống thanh toán (SenPay) an toàn.', 'Thương Mại Điện Tử', '700000', 'Tan Thuan EPZ, District 7, HCMC', 'sendo-logo.png', 'sendo.vn'),
(gen_random_uuid(), 'Got It', '0106728900', '50-150', 'Got It là một startup công nghệ hiếm hoi có trụ sở chính tại Thung lũng Silicon (Mỹ) nhưng toàn bộ đội ngũ kỹ sư R&D nòng cốt lại được đặt tại Việt Nam. Sản phẩm ban đầu của Got It là Nền tảng Giáo dục dưới dạng dịch vụ (Education as a Service), sử dụng Trí tuệ nhân tạo (AI) để kết nối tức thì người dùng với các chuyên gia nhằm giải quyết các bài toán khoa học. Gần đây, Got It đang dẫn đầu trong việc phát triển Conversational AI và Generative AI cho khách hàng doanh nghiệp, giúp biến kho dữ liệu khổng lồ thành trợ lý ảo thông minh. Môi trường tại Got It nổi tiếng khắt khe, tiệm cận với chuẩn mực của các Big Tech toàn cầu.', 'Công Nghệ Thông Tin', '100000', 'Trang Thi, Hoan Kiem, Hanoi', 'gotit-logo.png', 'gotit.ai'),
(gen_random_uuid(), 'Orient Software', '0303986971', '150-500', 'Thành lập năm 2005, Orient Software là một trong những công ty tư nhân chuyên cung cấp dịch vụ gia công và phát triển phần mềm (IT Outsourcing) lâu đời và uy tín tại Việt Nam. Công ty tập trung phát triển các ứng dụng phần mềm cho doanh nghiệp, ứng dụng web, ứng dụng di động, giải pháp AI/Machine Learning và IoT. Với hơn 15 năm kinh nghiệm, Orient đã mở rộng quy mô với nhiều chi nhánh tại Việt Nam và văn phòng đại diện ở nước ngoài (Nhật Bản, Singapore). Công ty cam kết quy trình quản lý chất lượng khắt khe chuẩn ISO, phục vụ mạng lưới khách hàng trải dài trên toàn thế giới.', 'Công Nghệ Thông Tin', '700000', 'District 4, HCMC', 'orient-logo.png', 'orientsoftware.com');

-- ========================================================
-- 2. SKILLS (10 records - Professional tech stack)
-- ========================================================
INSERT INTO skills (skills_name) VALUES
('Java Spring Boot'),
('React.js'),
('Node.js'),
('Python Django'),
('Docker Kubernetes'),
('PostgreSQL'),
('AWS Cloud'),
('Microservices'),
('CI/CD Jenkins'),
('GitOps ArgoCD');

-- ========================================================
-- 3. EXPERIENCE (10 records - LinkedIn-style professional)
-- ========================================================

INSERT INTO experience (company_id, headline, employment_type, start_date, end_date, description, location_type, employment_location, employment_industry, is_current) VALUES
-- FPT Software (Senior role)
((SELECT company_id FROM company WHERE company_name='FPT Software'), 'Senior Backend Engineer', 'FULL_TIME', '2023-04-01', NULL, 'Led 5-dev team building microservices with Spring Boot + PostgreSQL. Optimized database queries reducing latency 65%. Dockerized deployments to AWS EKS.', 'HYBRID', 'Ho Chi Minh City', 'IT Services', true),

-- VNG (Frontend)
((SELECT company_id FROM company WHERE company_name='VNG Corporation'), 'React Frontend Developer', 'FULL_TIME', '2022-07-01', '2024-12-31', 'Developed Zalo web dashboard with React/Redux. Handled 2M+ DAU, implemented real-time notifications with WebSockets.', 'REMOTE', 'Ho Chi Minh City', 'Technology', false),

-- Tiki (Fullstack)
((SELECT company_id FROM company WHERE company_name='Tiki Corporation'), 'Fullstack Engineer', 'FULL_TIME', '2021-03-01', '2023-03-31', 'Built e-commerce checkout flow with Node.js + React. Integrated payment gateways (VNPay, Momo), improved conversion rate 25%.', 'ON_SITE', 'Ho Chi Minh City', 'E-commerce', false),

-- VinAI (ML)
((SELECT company_id FROM company WHERE company_name='VinAI Research'), 'ML Engineer', 'FULL_TIME', '2022-09-01', NULL, 'Developed computer vision models for autonomous driving. PyTorch deployment on edge devices, achieved 92% mAP on custom dataset.', 'HYBRID', 'Hanoi', 'AI/ML', true),

-- CMC Global (Tech Lead)
((SELECT company_id FROM company WHERE company_name='CMC Global'), 'Tech Lead', 'FULL_TIME', '2023-01-01', '2025-02-28', 'Led offshore team for Japanese bank digital transformation. Migrated monolith to Kubernetes microservices.', 'HYBRID', 'Hanoi', 'IT Services', false),

-- Saigon Technology (DevOps)
((SELECT company_id FROM company WHERE company_name='Saigon Technology'), 'DevOps Engineer', 'FULL_TIME', '2021-11-01', '2023-10-31', 'Implemented CI/CD pipelines with Jenkins/GitLab. Managed AWS infrastructure for fintech clients, reduced deployment time 80%.', 'REMOTE', 'Ho Chi Minh City', 'Software Development', false),

-- KMS (QA Lead)
((SELECT company_id FROM company WHERE company_name='KMS Technology'), 'QA Automation Lead', 'FULL_TIME', '2020-06-01', '2022-05-31', 'Automated testing frameworks with Selenium/Cypress. Google Cloud integration testing for enterprise clients.', 'ON_SITE', 'Ho Chi Minh City', 'IT Services', false),

-- TMA (Software Engineer)
((SELECT company_id FROM company WHERE company_name='TMA Solutions'), 'Software Engineer II', 'FULL_TIME', '2022-02-01', NULL, 'Java backend for US healthcare SaaS. REST APIs + Oracle DB optimization, HIPAA compliant.', 'HYBRID', 'Ho Chi Minh City', 'IT Outsourcing', true),

-- Axon Active (Offshore Dev)
((SELECT company_id FROM company WHERE company_name='Axon Active'), '.NET Developer', 'FULL_TIME', '2019-09-01', '2021-08-31', 'Offshore projects for Swiss fintech. C# ASP.NET Core + Azure DevOps.', 'ON_SITE', 'Da Nang', 'IT Services', false),

-- Rikkeisoft (Backend)
((SELECT company_id FROM company WHERE company_name='Rikkeisoft'), 'Backend Developer', 'FULL_TIME', '2021-08-01', '2023-07-31', 'Enterprise systems for Japanese clients. Spring Boot + MySQL, handled 10k+ TPS.', 'ON_SITE', 'Hanoi', 'IT Services', false);

